In [1]:
import numpy as np


In [2]:
a=np.array([(4,2,3),(1,5,0),(7,8,6)])
a

array([[4, 2, 3],
       [1, 5, 0],
       [7, 8, 6]])

In [3]:
np.linalg.det(a)


26.99999999999999

In [26]:
d1
w=[]
n_linhas=3
n_colunas=3
for l in range(n_linhas):
  for c in range(n_colunas):
    if l<=0:
      w.append(a[(l)][(c)])
    else:
      w[((-1)*(l-c))]=w[((-1)*(l-c))]*a[(l)][(c)]

d1=sum(w)
w=[]
for l in range(n_linhas):
  for c in range(n_colunas):
    if l<=0:
      w.append(a[(l)][(c)])
    else:
      if (l+c)<n_linhas:
        w[(l+c)]=w[(l+c)]*a[(l)][(c)]
      else:
        w[((l+c)-n_linhas)]= w[((l+c)-n_linhas)]*a[(l)][(c)]


d2=sum(w)
det=d1-d2
print(a)
print("DET = {}".format(det))


[[4 2 3]
 [1 5 0]
 [7 8 6]]
DET = 27
